package com.gojava.db.dao;

import com.gojava.db.model.VipConfig;
import com.gojava.db.model.VipConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int countByExample(VipConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int deleteByExample(VipConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int insert(VipConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int insertSelective(VipConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    List<VipConfig> selectByExample(VipConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    VipConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") VipConfig record, @Param("example") VipConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByExample(@Param("record") VipConfig record, @Param("example") VipConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByPrimaryKeySelective(VipConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_config
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByPrimaryKey(VipConfig record);
}