package com.gojava.db.dao;

import com.gojava.db.model.OrderFirstChargeLog;
import com.gojava.db.model.OrderFirstChargeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderFirstChargeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int countByExample(OrderFirstChargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int deleteByExample(OrderFirstChargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int insert(OrderFirstChargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int insertSelective(OrderFirstChargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    List<OrderFirstChargeLog> selectByExample(OrderFirstChargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    OrderFirstChargeLog selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderFirstChargeLog record, @Param("example") OrderFirstChargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByExample(@Param("record") OrderFirstChargeLog record, @Param("example") OrderFirstChargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByPrimaryKeySelective(OrderFirstChargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_first_charge_log
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    int updateByPrimaryKey(OrderFirstChargeLog record);
}