package com.gojava.db.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class UserExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("OpenId is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("OpenId is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("OpenId =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("OpenId <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("OpenId >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("OpenId >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("OpenId <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("OpenId <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("OpenId like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("OpenId not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("OpenId in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("OpenId not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("OpenId between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("OpenId not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andNikeIsNull() {
            addCriterion("Nike is null");
            return (Criteria) this;
        }

        public Criteria andNikeIsNotNull() {
            addCriterion("Nike is not null");
            return (Criteria) this;
        }

        public Criteria andNikeEqualTo(String value) {
            addCriterion("Nike =", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeNotEqualTo(String value) {
            addCriterion("Nike <>", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeGreaterThan(String value) {
            addCriterion("Nike >", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeGreaterThanOrEqualTo(String value) {
            addCriterion("Nike >=", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeLessThan(String value) {
            addCriterion("Nike <", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeLessThanOrEqualTo(String value) {
            addCriterion("Nike <=", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeLike(String value) {
            addCriterion("Nike like", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeNotLike(String value) {
            addCriterion("Nike not like", value, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeIn(List<String> values) {
            addCriterion("Nike in", values, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeNotIn(List<String> values) {
            addCriterion("Nike not in", values, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeBetween(String value1, String value2) {
            addCriterion("Nike between", value1, value2, "nike");
            return (Criteria) this;
        }

        public Criteria andNikeNotBetween(String value1, String value2) {
            addCriterion("Nike not between", value1, value2, "nike");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("Sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("Sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("Sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("Sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("Sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("Sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("Sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("Sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("Sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("Sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("Sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andProviceIsNull() {
            addCriterion("Provice is null");
            return (Criteria) this;
        }

        public Criteria andProviceIsNotNull() {
            addCriterion("Provice is not null");
            return (Criteria) this;
        }

        public Criteria andProviceEqualTo(String value) {
            addCriterion("Provice =", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotEqualTo(String value) {
            addCriterion("Provice <>", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceGreaterThan(String value) {
            addCriterion("Provice >", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceGreaterThanOrEqualTo(String value) {
            addCriterion("Provice >=", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceLessThan(String value) {
            addCriterion("Provice <", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceLessThanOrEqualTo(String value) {
            addCriterion("Provice <=", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceLike(String value) {
            addCriterion("Provice like", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotLike(String value) {
            addCriterion("Provice not like", value, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceIn(List<String> values) {
            addCriterion("Provice in", values, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotIn(List<String> values) {
            addCriterion("Provice not in", values, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceBetween(String value1, String value2) {
            addCriterion("Provice between", value1, value2, "provice");
            return (Criteria) this;
        }

        public Criteria andProviceNotBetween(String value1, String value2) {
            addCriterion("Provice not between", value1, value2, "provice");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("City is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("City is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("City =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("City <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("City >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("City >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("City <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("City <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("City like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("City not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("City in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("City not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("City between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("City not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("Country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("Country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("Country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("Country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("Country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("Country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("Country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("Country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("Country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("Country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("Country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("Country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("Country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("Country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlIsNull() {
            addCriterion("HeadImageUrl is null");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlIsNotNull() {
            addCriterion("HeadImageUrl is not null");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlEqualTo(String value) {
            addCriterion("HeadImageUrl =", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlNotEqualTo(String value) {
            addCriterion("HeadImageUrl <>", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlGreaterThan(String value) {
            addCriterion("HeadImageUrl >", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlGreaterThanOrEqualTo(String value) {
            addCriterion("HeadImageUrl >=", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlLessThan(String value) {
            addCriterion("HeadImageUrl <", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlLessThanOrEqualTo(String value) {
            addCriterion("HeadImageUrl <=", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlLike(String value) {
            addCriterion("HeadImageUrl like", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlNotLike(String value) {
            addCriterion("HeadImageUrl not like", value, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlIn(List<String> values) {
            addCriterion("HeadImageUrl in", values, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlNotIn(List<String> values) {
            addCriterion("HeadImageUrl not in", values, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlBetween(String value1, String value2) {
            addCriterion("HeadImageUrl between", value1, value2, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andHeadimageurlNotBetween(String value1, String value2) {
            addCriterion("HeadImageUrl not between", value1, value2, "headimageurl");
            return (Criteria) this;
        }

        public Criteria andUnionidIsNull() {
            addCriterion("UnionId is null");
            return (Criteria) this;
        }

        public Criteria andUnionidIsNotNull() {
            addCriterion("UnionId is not null");
            return (Criteria) this;
        }

        public Criteria andUnionidEqualTo(String value) {
            addCriterion("UnionId =", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotEqualTo(String value) {
            addCriterion("UnionId <>", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidGreaterThan(String value) {
            addCriterion("UnionId >", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidGreaterThanOrEqualTo(String value) {
            addCriterion("UnionId >=", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidLessThan(String value) {
            addCriterion("UnionId <", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidLessThanOrEqualTo(String value) {
            addCriterion("UnionId <=", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidLike(String value) {
            addCriterion("UnionId like", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotLike(String value) {
            addCriterion("UnionId not like", value, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidIn(List<String> values) {
            addCriterion("UnionId in", values, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotIn(List<String> values) {
            addCriterion("UnionId not in", values, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidBetween(String value1, String value2) {
            addCriterion("UnionId between", value1, value2, "unionid");
            return (Criteria) this;
        }

        public Criteria andUnionidNotBetween(String value1, String value2) {
            addCriterion("UnionId not between", value1, value2, "unionid");
            return (Criteria) this;
        }

        public Criteria andNumscard1IsNull() {
            addCriterion("NumsCard1 is null");
            return (Criteria) this;
        }

        public Criteria andNumscard1IsNotNull() {
            addCriterion("NumsCard1 is not null");
            return (Criteria) this;
        }

        public Criteria andNumscard1EqualTo(Integer value) {
            addCriterion("NumsCard1 =", value, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1NotEqualTo(Integer value) {
            addCriterion("NumsCard1 <>", value, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1GreaterThan(Integer value) {
            addCriterion("NumsCard1 >", value, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1GreaterThanOrEqualTo(Integer value) {
            addCriterion("NumsCard1 >=", value, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1LessThan(Integer value) {
            addCriterion("NumsCard1 <", value, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1LessThanOrEqualTo(Integer value) {
            addCriterion("NumsCard1 <=", value, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1In(List<Integer> values) {
            addCriterion("NumsCard1 in", values, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1NotIn(List<Integer> values) {
            addCriterion("NumsCard1 not in", values, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1Between(Integer value1, Integer value2) {
            addCriterion("NumsCard1 between", value1, value2, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard1NotBetween(Integer value1, Integer value2) {
            addCriterion("NumsCard1 not between", value1, value2, "numscard1");
            return (Criteria) this;
        }

        public Criteria andNumscard2IsNull() {
            addCriterion("NumsCard2 is null");
            return (Criteria) this;
        }

        public Criteria andNumscard2IsNotNull() {
            addCriterion("NumsCard2 is not null");
            return (Criteria) this;
        }

        public Criteria andNumscard2EqualTo(Integer value) {
            addCriterion("NumsCard2 =", value, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2NotEqualTo(Integer value) {
            addCriterion("NumsCard2 <>", value, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2GreaterThan(Integer value) {
            addCriterion("NumsCard2 >", value, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2GreaterThanOrEqualTo(Integer value) {
            addCriterion("NumsCard2 >=", value, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2LessThan(Integer value) {
            addCriterion("NumsCard2 <", value, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2LessThanOrEqualTo(Integer value) {
            addCriterion("NumsCard2 <=", value, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2In(List<Integer> values) {
            addCriterion("NumsCard2 in", values, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2NotIn(List<Integer> values) {
            addCriterion("NumsCard2 not in", values, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2Between(Integer value1, Integer value2) {
            addCriterion("NumsCard2 between", value1, value2, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard2NotBetween(Integer value1, Integer value2) {
            addCriterion("NumsCard2 not between", value1, value2, "numscard2");
            return (Criteria) this;
        }

        public Criteria andNumscard3IsNull() {
            addCriterion("NumsCard3 is null");
            return (Criteria) this;
        }

        public Criteria andNumscard3IsNotNull() {
            addCriterion("NumsCard3 is not null");
            return (Criteria) this;
        }

        public Criteria andNumscard3EqualTo(Integer value) {
            addCriterion("NumsCard3 =", value, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3NotEqualTo(Integer value) {
            addCriterion("NumsCard3 <>", value, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3GreaterThan(Integer value) {
            addCriterion("NumsCard3 >", value, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3GreaterThanOrEqualTo(Integer value) {
            addCriterion("NumsCard3 >=", value, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3LessThan(Integer value) {
            addCriterion("NumsCard3 <", value, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3LessThanOrEqualTo(Integer value) {
            addCriterion("NumsCard3 <=", value, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3In(List<Integer> values) {
            addCriterion("NumsCard3 in", values, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3NotIn(List<Integer> values) {
            addCriterion("NumsCard3 not in", values, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3Between(Integer value1, Integer value2) {
            addCriterion("NumsCard3 between", value1, value2, "numscard3");
            return (Criteria) this;
        }

        public Criteria andNumscard3NotBetween(Integer value1, Integer value2) {
            addCriterion("NumsCard3 not between", value1, value2, "numscard3");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNull() {
            addCriterion("LastLoginTime is null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNotNull() {
            addCriterion("LastLoginTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeEqualTo(Integer value) {
            addCriterion("LastLoginTime =", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotEqualTo(Integer value) {
            addCriterion("LastLoginTime <>", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThan(Integer value) {
            addCriterion("LastLoginTime >", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("LastLoginTime >=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThan(Integer value) {
            addCriterion("LastLoginTime <", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThanOrEqualTo(Integer value) {
            addCriterion("LastLoginTime <=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIn(List<Integer> values) {
            addCriterion("LastLoginTime in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotIn(List<Integer> values) {
            addCriterion("LastLoginTime not in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeBetween(Integer value1, Integer value2) {
            addCriterion("LastLoginTime between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotBetween(Integer value1, Integer value2) {
            addCriterion("LastLoginTime not between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andRegtimeIsNull() {
            addCriterion("RegTime is null");
            return (Criteria) this;
        }

        public Criteria andRegtimeIsNotNull() {
            addCriterion("RegTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegtimeEqualTo(Integer value) {
            addCriterion("RegTime =", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotEqualTo(Integer value) {
            addCriterion("RegTime <>", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeGreaterThan(Integer value) {
            addCriterion("RegTime >", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("RegTime >=", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeLessThan(Integer value) {
            addCriterion("RegTime <", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeLessThanOrEqualTo(Integer value) {
            addCriterion("RegTime <=", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeIn(List<Integer> values) {
            addCriterion("RegTime in", values, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotIn(List<Integer> values) {
            addCriterion("RegTime not in", values, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeBetween(Integer value1, Integer value2) {
            addCriterion("RegTime between", value1, value2, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("RegTime not between", value1, value2, "regtime");
            return (Criteria) this;
        }

        public Criteria andNewIsNull() {
            addCriterion("New is null");
            return (Criteria) this;
        }

        public Criteria andNewIsNotNull() {
            addCriterion("New is not null");
            return (Criteria) this;
        }

        public Criteria andNewEqualTo(Integer value) {
            addCriterion("New =", value, "new");
            return (Criteria) this;
        }

        public Criteria andNewNotEqualTo(Integer value) {
            addCriterion("New <>", value, "new");
            return (Criteria) this;
        }

        public Criteria andNewGreaterThan(Integer value) {
            addCriterion("New >", value, "new");
            return (Criteria) this;
        }

        public Criteria andNewGreaterThanOrEqualTo(Integer value) {
            addCriterion("New >=", value, "new");
            return (Criteria) this;
        }

        public Criteria andNewLessThan(Integer value) {
            addCriterion("New <", value, "new");
            return (Criteria) this;
        }

        public Criteria andNewLessThanOrEqualTo(Integer value) {
            addCriterion("New <=", value, "new");
            return (Criteria) this;
        }

        public Criteria andNewIn(List<Integer> values) {
            addCriterion("New in", values, "new");
            return (Criteria) this;
        }

        public Criteria andNewNotIn(List<Integer> values) {
            addCriterion("New not in", values, "new");
            return (Criteria) this;
        }

        public Criteria andNewBetween(Integer value1, Integer value2) {
            addCriterion("New between", value1, value2, "new");
            return (Criteria) this;
        }

        public Criteria andNewNotBetween(Integer value1, Integer value2) {
            addCriterion("New not between", value1, value2, "new");
            return (Criteria) this;
        }

        public Criteria andGmIsNull() {
            addCriterion("Gm is null");
            return (Criteria) this;
        }

        public Criteria andGmIsNotNull() {
            addCriterion("Gm is not null");
            return (Criteria) this;
        }

        public Criteria andGmEqualTo(Integer value) {
            addCriterion("Gm =", value, "gm");
            return (Criteria) this;
        }

        public Criteria andGmNotEqualTo(Integer value) {
            addCriterion("Gm <>", value, "gm");
            return (Criteria) this;
        }

        public Criteria andGmGreaterThan(Integer value) {
            addCriterion("Gm >", value, "gm");
            return (Criteria) this;
        }

        public Criteria andGmGreaterThanOrEqualTo(Integer value) {
            addCriterion("Gm >=", value, "gm");
            return (Criteria) this;
        }

        public Criteria andGmLessThan(Integer value) {
            addCriterion("Gm <", value, "gm");
            return (Criteria) this;
        }

        public Criteria andGmLessThanOrEqualTo(Integer value) {
            addCriterion("Gm <=", value, "gm");
            return (Criteria) this;
        }

        public Criteria andGmIn(List<Integer> values) {
            addCriterion("Gm in", values, "gm");
            return (Criteria) this;
        }

        public Criteria andGmNotIn(List<Integer> values) {
            addCriterion("Gm not in", values, "gm");
            return (Criteria) this;
        }

        public Criteria andGmBetween(Integer value1, Integer value2) {
            addCriterion("Gm between", value1, value2, "gm");
            return (Criteria) this;
        }

        public Criteria andGmNotBetween(Integer value1, Integer value2) {
            addCriterion("Gm not between", value1, value2, "gm");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumIsNull() {
            addCriterion("TotalCardNum is null");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumIsNotNull() {
            addCriterion("TotalCardNum is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumEqualTo(Integer value) {
            addCriterion("TotalCardNum =", value, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumNotEqualTo(Integer value) {
            addCriterion("TotalCardNum <>", value, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumGreaterThan(Integer value) {
            addCriterion("TotalCardNum >", value, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("TotalCardNum >=", value, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumLessThan(Integer value) {
            addCriterion("TotalCardNum <", value, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumLessThanOrEqualTo(Integer value) {
            addCriterion("TotalCardNum <=", value, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumIn(List<Integer> values) {
            addCriterion("TotalCardNum in", values, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumNotIn(List<Integer> values) {
            addCriterion("TotalCardNum not in", values, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumBetween(Integer value1, Integer value2) {
            addCriterion("TotalCardNum between", value1, value2, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalcardnumNotBetween(Integer value1, Integer value2) {
            addCriterion("TotalCardNum not between", value1, value2, "totalcardnum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumIsNull() {
            addCriterion("TotalPlayNum is null");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumIsNotNull() {
            addCriterion("TotalPlayNum is not null");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumEqualTo(Integer value) {
            addCriterion("TotalPlayNum =", value, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumNotEqualTo(Integer value) {
            addCriterion("TotalPlayNum <>", value, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumGreaterThan(Integer value) {
            addCriterion("TotalPlayNum >", value, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumGreaterThanOrEqualTo(Integer value) {
            addCriterion("TotalPlayNum >=", value, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumLessThan(Integer value) {
            addCriterion("TotalPlayNum <", value, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumLessThanOrEqualTo(Integer value) {
            addCriterion("TotalPlayNum <=", value, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumIn(List<Integer> values) {
            addCriterion("TotalPlayNum in", values, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumNotIn(List<Integer> values) {
            addCriterion("TotalPlayNum not in", values, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumBetween(Integer value1, Integer value2) {
            addCriterion("TotalPlayNum between", value1, value2, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andTotalplaynumNotBetween(Integer value1, Integer value2) {
            addCriterion("TotalPlayNum not between", value1, value2, "totalplaynum");
            return (Criteria) this;
        }

        public Criteria andCoinsIsNull() {
            addCriterion("Coins is null");
            return (Criteria) this;
        }

        public Criteria andCoinsIsNotNull() {
            addCriterion("Coins is not null");
            return (Criteria) this;
        }

        public Criteria andCoinsEqualTo(Integer value) {
            addCriterion("Coins =", value, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsNotEqualTo(Integer value) {
            addCriterion("Coins <>", value, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsGreaterThan(Integer value) {
            addCriterion("Coins >", value, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsGreaterThanOrEqualTo(Integer value) {
            addCriterion("Coins >=", value, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsLessThan(Integer value) {
            addCriterion("Coins <", value, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsLessThanOrEqualTo(Integer value) {
            addCriterion("Coins <=", value, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsIn(List<Integer> values) {
            addCriterion("Coins in", values, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsNotIn(List<Integer> values) {
            addCriterion("Coins not in", values, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsBetween(Integer value1, Integer value2) {
            addCriterion("Coins between", value1, value2, "coins");
            return (Criteria) this;
        }

        public Criteria andCoinsNotBetween(Integer value1, Integer value2) {
            addCriterion("Coins not between", value1, value2, "coins");
            return (Criteria) this;
        }

        public Criteria andCreditsIsNull() {
            addCriterion("Credits is null");
            return (Criteria) this;
        }

        public Criteria andCreditsIsNotNull() {
            addCriterion("Credits is not null");
            return (Criteria) this;
        }

        public Criteria andCreditsEqualTo(Integer value) {
            addCriterion("Credits =", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotEqualTo(Integer value) {
            addCriterion("Credits <>", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsGreaterThan(Integer value) {
            addCriterion("Credits >", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsGreaterThanOrEqualTo(Integer value) {
            addCriterion("Credits >=", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsLessThan(Integer value) {
            addCriterion("Credits <", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsLessThanOrEqualTo(Integer value) {
            addCriterion("Credits <=", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsIn(List<Integer> values) {
            addCriterion("Credits in", values, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotIn(List<Integer> values) {
            addCriterion("Credits not in", values, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsBetween(Integer value1, Integer value2) {
            addCriterion("Credits between", value1, value2, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotBetween(Integer value1, Integer value2) {
            addCriterion("Credits not between", value1, value2, "credits");
            return (Criteria) this;
        }

        public Criteria andDiamondIsNull() {
            addCriterion("Diamond is null");
            return (Criteria) this;
        }

        public Criteria andDiamondIsNotNull() {
            addCriterion("Diamond is not null");
            return (Criteria) this;
        }

        public Criteria andDiamondEqualTo(Integer value) {
            addCriterion("Diamond =", value, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondNotEqualTo(Integer value) {
            addCriterion("Diamond <>", value, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondGreaterThan(Integer value) {
            addCriterion("Diamond >", value, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondGreaterThanOrEqualTo(Integer value) {
            addCriterion("Diamond >=", value, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondLessThan(Integer value) {
            addCriterion("Diamond <", value, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondLessThanOrEqualTo(Integer value) {
            addCriterion("Diamond <=", value, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondIn(List<Integer> values) {
            addCriterion("Diamond in", values, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondNotIn(List<Integer> values) {
            addCriterion("Diamond not in", values, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondBetween(Integer value1, Integer value2) {
            addCriterion("Diamond between", value1, value2, "diamond");
            return (Criteria) this;
        }

        public Criteria andDiamondNotBetween(Integer value1, Integer value2) {
            addCriterion("Diamond not between", value1, value2, "diamond");
            return (Criteria) this;
        }

        public Criteria andRegisterIpIsNull() {
            addCriterion("register_ip is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIpIsNotNull() {
            addCriterion("register_ip is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIpEqualTo(String value) {
            addCriterion("register_ip =", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotEqualTo(String value) {
            addCriterion("register_ip <>", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpGreaterThan(String value) {
            addCriterion("register_ip >", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpGreaterThanOrEqualTo(String value) {
            addCriterion("register_ip >=", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpLessThan(String value) {
            addCriterion("register_ip <", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpLessThanOrEqualTo(String value) {
            addCriterion("register_ip <=", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpLike(String value) {
            addCriterion("register_ip like", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotLike(String value) {
            addCriterion("register_ip not like", value, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpIn(List<String> values) {
            addCriterion("register_ip in", values, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotIn(List<String> values) {
            addCriterion("register_ip not in", values, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpBetween(String value1, String value2) {
            addCriterion("register_ip between", value1, value2, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegisterIpNotBetween(String value1, String value2) {
            addCriterion("register_ip not between", value1, value2, "registerIp");
            return (Criteria) this;
        }

        public Criteria andRegMacIsNull() {
            addCriterion("reg_mac is null");
            return (Criteria) this;
        }

        public Criteria andRegMacIsNotNull() {
            addCriterion("reg_mac is not null");
            return (Criteria) this;
        }

        public Criteria andRegMacEqualTo(String value) {
            addCriterion("reg_mac =", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacNotEqualTo(String value) {
            addCriterion("reg_mac <>", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacGreaterThan(String value) {
            addCriterion("reg_mac >", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacGreaterThanOrEqualTo(String value) {
            addCriterion("reg_mac >=", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacLessThan(String value) {
            addCriterion("reg_mac <", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacLessThanOrEqualTo(String value) {
            addCriterion("reg_mac <=", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacLike(String value) {
            addCriterion("reg_mac like", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacNotLike(String value) {
            addCriterion("reg_mac not like", value, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacIn(List<String> values) {
            addCriterion("reg_mac in", values, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacNotIn(List<String> values) {
            addCriterion("reg_mac not in", values, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacBetween(String value1, String value2) {
            addCriterion("reg_mac between", value1, value2, "regMac");
            return (Criteria) this;
        }

        public Criteria andRegMacNotBetween(String value1, String value2) {
            addCriterion("reg_mac not between", value1, value2, "regMac");
            return (Criteria) this;
        }

        public Criteria andSpreadIdIsNull() {
            addCriterion("spread_id is null");
            return (Criteria) this;
        }

        public Criteria andSpreadIdIsNotNull() {
            addCriterion("spread_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadIdEqualTo(Integer value) {
            addCriterion("spread_id =", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdNotEqualTo(Integer value) {
            addCriterion("spread_id <>", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdGreaterThan(Integer value) {
            addCriterion("spread_id >", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("spread_id >=", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdLessThan(Integer value) {
            addCriterion("spread_id <", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdLessThanOrEqualTo(Integer value) {
            addCriterion("spread_id <=", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdIn(List<Integer> values) {
            addCriterion("spread_id in", values, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdNotIn(List<Integer> values) {
            addCriterion("spread_id not in", values, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdBetween(Integer value1, Integer value2) {
            addCriterion("spread_id between", value1, value2, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdNotBetween(Integer value1, Integer value2) {
            addCriterion("spread_id not between", value1, value2, "spreadId");
            return (Criteria) this;
        }

        public Criteria andRegChannelIsNull() {
            addCriterion("reg_channel is null");
            return (Criteria) this;
        }

        public Criteria andRegChannelIsNotNull() {
            addCriterion("reg_channel is not null");
            return (Criteria) this;
        }

        public Criteria andRegChannelEqualTo(String value) {
            addCriterion("reg_channel =", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelNotEqualTo(String value) {
            addCriterion("reg_channel <>", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelGreaterThan(String value) {
            addCriterion("reg_channel >", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelGreaterThanOrEqualTo(String value) {
            addCriterion("reg_channel >=", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelLessThan(String value) {
            addCriterion("reg_channel <", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelLessThanOrEqualTo(String value) {
            addCriterion("reg_channel <=", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelLike(String value) {
            addCriterion("reg_channel like", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelNotLike(String value) {
            addCriterion("reg_channel not like", value, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelIn(List<String> values) {
            addCriterion("reg_channel in", values, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelNotIn(List<String> values) {
            addCriterion("reg_channel not in", values, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelBetween(String value1, String value2) {
            addCriterion("reg_channel between", value1, value2, "regChannel");
            return (Criteria) this;
        }

        public Criteria andRegChannelNotBetween(String value1, String value2) {
            addCriterion("reg_channel not between", value1, value2, "regChannel");
            return (Criteria) this;
        }

        public Criteria andInviterIdIsNull() {
            addCriterion("inviter_id is null");
            return (Criteria) this;
        }

        public Criteria andInviterIdIsNotNull() {
            addCriterion("inviter_id is not null");
            return (Criteria) this;
        }

        public Criteria andInviterIdEqualTo(Integer value) {
            addCriterion("inviter_id =", value, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdNotEqualTo(Integer value) {
            addCriterion("inviter_id <>", value, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdGreaterThan(Integer value) {
            addCriterion("inviter_id >", value, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("inviter_id >=", value, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdLessThan(Integer value) {
            addCriterion("inviter_id <", value, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdLessThanOrEqualTo(Integer value) {
            addCriterion("inviter_id <=", value, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdIn(List<Integer> values) {
            addCriterion("inviter_id in", values, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdNotIn(List<Integer> values) {
            addCriterion("inviter_id not in", values, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdBetween(Integer value1, Integer value2) {
            addCriterion("inviter_id between", value1, value2, "inviterId");
            return (Criteria) this;
        }

        public Criteria andInviterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("inviter_id not between", value1, value2, "inviterId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdIsNull() {
            addCriterion("general_id is null");
            return (Criteria) this;
        }

        public Criteria andGeneralIdIsNotNull() {
            addCriterion("general_id is not null");
            return (Criteria) this;
        }

        public Criteria andGeneralIdEqualTo(Long value) {
            addCriterion("general_id =", value, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdNotEqualTo(Long value) {
            addCriterion("general_id <>", value, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdGreaterThan(Long value) {
            addCriterion("general_id >", value, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdGreaterThanOrEqualTo(Long value) {
            addCriterion("general_id >=", value, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdLessThan(Long value) {
            addCriterion("general_id <", value, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdLessThanOrEqualTo(Long value) {
            addCriterion("general_id <=", value, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdIn(List<Long> values) {
            addCriterion("general_id in", values, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdNotIn(List<Long> values) {
            addCriterion("general_id not in", values, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdBetween(Long value1, Long value2) {
            addCriterion("general_id between", value1, value2, "generalId");
            return (Criteria) this;
        }

        public Criteria andGeneralIdNotBetween(Long value1, Long value2) {
            addCriterion("general_id not between", value1, value2, "generalId");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagIsNull() {
            addCriterion("period_email_flag is null");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagIsNotNull() {
            addCriterion("period_email_flag is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagEqualTo(String value) {
            addCriterion("period_email_flag =", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagNotEqualTo(String value) {
            addCriterion("period_email_flag <>", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagGreaterThan(String value) {
            addCriterion("period_email_flag >", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagGreaterThanOrEqualTo(String value) {
            addCriterion("period_email_flag >=", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagLessThan(String value) {
            addCriterion("period_email_flag <", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagLessThanOrEqualTo(String value) {
            addCriterion("period_email_flag <=", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagLike(String value) {
            addCriterion("period_email_flag like", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagNotLike(String value) {
            addCriterion("period_email_flag not like", value, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagIn(List<String> values) {
            addCriterion("period_email_flag in", values, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagNotIn(List<String> values) {
            addCriterion("period_email_flag not in", values, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagBetween(String value1, String value2) {
            addCriterion("period_email_flag between", value1, value2, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPeriodEmailFlagNotBetween(String value1, String value2) {
            addCriterion("period_email_flag not between", value1, value2, "periodEmailFlag");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 26 21:19:14 CST 2017
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}