package com.gojava.db.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.OpenId
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Nike
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String nike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Sex
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Provice
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String provice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.City
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Country
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.HeadImageUrl
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String headimageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UnionId
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NumsCard1
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer numscard1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NumsCard2
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer numscard2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NumsCard3
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer numscard3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LastLoginTime
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.RegTime
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.New
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer New;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Gm
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer gm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TotalCardNum
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer totalcardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TotalPlayNum
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer totalplaynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Coins
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer coins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Credits
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer credits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Diamond
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer diamond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_ip
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_mac
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String regMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.spread_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer spreadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_channel
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String regChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.inviter_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Integer inviterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.general_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private Long generalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.period_email_flag
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String periodEmailFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_number
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Id
     *
     * @return the value of user.Id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Id
     *
     * @param id the value for user.Id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.OpenId
     *
     * @return the value of user.OpenId
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.OpenId
     *
     * @param openid the value for user.OpenId
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Nike
     *
     * @return the value of user.Nike
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getNike() {
        return nike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Nike
     *
     * @param nike the value for user.Nike
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setNike(String nike) {
        this.nike = nike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Sex
     *
     * @return the value of user.Sex
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Sex
     *
     * @param sex the value for user.Sex
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Provice
     *
     * @return the value of user.Provice
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getProvice() {
        return provice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Provice
     *
     * @param provice the value for user.Provice
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setProvice(String provice) {
        this.provice = provice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.City
     *
     * @return the value of user.City
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.City
     *
     * @param city the value for user.City
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Country
     *
     * @return the value of user.Country
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Country
     *
     * @param country the value for user.Country
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.HeadImageUrl
     *
     * @return the value of user.HeadImageUrl
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getHeadimageurl() {
        return headimageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.HeadImageUrl
     *
     * @param headimageurl the value for user.HeadImageUrl
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setHeadimageurl(String headimageurl) {
        this.headimageurl = headimageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UnionId
     *
     * @return the value of user.UnionId
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UnionId
     *
     * @param unionid the value for user.UnionId
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NumsCard1
     *
     * @return the value of user.NumsCard1
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getNumscard1() {
        return numscard1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NumsCard1
     *
     * @param numscard1 the value for user.NumsCard1
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setNumscard1(Integer numscard1) {
        this.numscard1 = numscard1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NumsCard2
     *
     * @return the value of user.NumsCard2
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getNumscard2() {
        return numscard2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NumsCard2
     *
     * @param numscard2 the value for user.NumsCard2
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setNumscard2(Integer numscard2) {
        this.numscard2 = numscard2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NumsCard3
     *
     * @return the value of user.NumsCard3
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getNumscard3() {
        return numscard3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NumsCard3
     *
     * @param numscard3 the value for user.NumsCard3
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setNumscard3(Integer numscard3) {
        this.numscard3 = numscard3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LastLoginTime
     *
     * @return the value of user.LastLoginTime
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LastLoginTime
     *
     * @param lastlogintime the value for user.LastLoginTime
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setLastlogintime(Integer lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.RegTime
     *
     * @return the value of user.RegTime
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.RegTime
     *
     * @param regtime the value for user.RegTime
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setRegtime(Integer regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Gm
     *
     * @return the value of user.Gm
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getGm() {
        return gm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Gm
     *
     * @param gm the value for user.Gm
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setGm(Integer gm) {
        this.gm = gm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TotalCardNum
     *
     * @return the value of user.TotalCardNum
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getTotalcardnum() {
        return totalcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TotalCardNum
     *
     * @param totalcardnum the value for user.TotalCardNum
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setTotalcardnum(Integer totalcardnum) {
        this.totalcardnum = totalcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TotalPlayNum
     *
     * @return the value of user.TotalPlayNum
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getTotalplaynum() {
        return totalplaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TotalPlayNum
     *
     * @param totalplaynum the value for user.TotalPlayNum
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setTotalplaynum(Integer totalplaynum) {
        this.totalplaynum = totalplaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Coins
     *
     * @return the value of user.Coins
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getCoins() {
        return coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Coins
     *
     * @param coins the value for user.Coins
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setCoins(Integer coins) {
        this.coins = coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Credits
     *
     * @return the value of user.Credits
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Credits
     *
     * @param credits the value for user.Credits
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Diamond
     *
     * @return the value of user.Diamond
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getDiamond() {
        return diamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Diamond
     *
     * @param diamond the value for user.Diamond
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setDiamond(Integer diamond) {
        this.diamond = diamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_ip
     *
     * @return the value of user.register_ip
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_ip
     *
     * @param registerIp the value for user.register_ip
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_mac
     *
     * @return the value of user.reg_mac
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getRegMac() {
        return regMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_mac
     *
     * @param regMac the value for user.reg_mac
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setRegMac(String regMac) {
        this.regMac = regMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.spread_id
     *
     * @return the value of user.spread_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getSpreadId() {
        return spreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.spread_id
     *
     * @param spreadId the value for user.spread_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setSpreadId(Integer spreadId) {
        this.spreadId = spreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_channel
     *
     * @return the value of user.reg_channel
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getRegChannel() {
        return regChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_channel
     *
     * @param regChannel the value for user.reg_channel
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setRegChannel(String regChannel) {
        this.regChannel = regChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.inviter_id
     *
     * @return the value of user.inviter_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Integer getInviterId() {
        return inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.inviter_id
     *
     * @param inviterId the value for user.inviter_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setInviterId(Integer inviterId) {
        this.inviterId = inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.general_id
     *
     * @return the value of user.general_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public Long getGeneralId() {
        return generalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.general_id
     *
     * @param generalId the value for user.general_id
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setGeneralId(Long generalId) {
        this.generalId = generalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.period_email_flag
     *
     * @return the value of user.period_email_flag
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getPeriodEmailFlag() {
        return periodEmailFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.period_email_flag
     *
     * @param periodEmailFlag the value for user.period_email_flag
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setPeriodEmailFlag(String periodEmailFlag) {
        this.periodEmailFlag = periodEmailFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_number
     *
     * @return the value of user.phone_number
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_number
     *
     * @param phoneNumber the value for user.phone_number
     *
     * @mbggenerated Tue Dec 26 21:19:14 CST 2017
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    private User(Builder b) {
        id = b.id;
        openid = b.openid;
        nike = b.nike;
        sex = b.sex;
        provice = b.provice;
        city = b.city;
        country = b.country;
        headimageurl = b.headimageurl;
        unionid = b.unionid;
        numscard1 = b.numscard1;
        numscard2 = b.numscard2;
        numscard3 = b.numscard3;
        lastlogintime = b.lastlogintime;
        regtime = b.regtime;
        gm = b.gm;
        totalcardnum = b.totalcardnum;
        totalplaynum = b.totalplaynum;
        coins = b.coins;
        credits = b.credits;
        diamond = b.diamond;
        registerIp = b.registerIp;
        regMac = b.regMac;
        spreadId = b.spreadId;
        regChannel = b.regChannel;
        inviterId = b.inviterId;
        generalId = b.generalId;
        periodEmailFlag = b.periodEmailFlag;
        phoneNumber = b.phoneNumber;
    }

    public User() {
        super();
    }

    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Id
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer id;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.OpenId
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String openid;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Nike
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String nike;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Sex
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer sex;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Provice
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String provice;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.City
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String city;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Country
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String country;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.HeadImageUrl
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String headimageurl;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.UnionId
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String unionid;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.NumsCard1
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer numscard1;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.NumsCard2
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer numscard2;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.NumsCard3
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer numscard3;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.LastLoginTime
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer lastlogintime;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.RegTime
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer regtime;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Gm
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer gm;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.TotalCardNum
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer totalcardnum;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.TotalPlayNum
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer totalplaynum;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Coins
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer coins;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Credits
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer credits;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.Diamond
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer diamond;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.register_ip
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String registerIp;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.reg_mac
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String regMac;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.spread_id
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer spreadId;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.reg_channel
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String regChannel;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.inviter_id
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Integer inviterId;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.general_id
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private Long generalId;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.period_email_flag
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String periodEmailFlag;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user.phone_number
         *
         * @mbggenerated Tue Dec 26 21:19:14 CST 2017
         */
        private String phoneNumber;

        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        public Builder openid(String openid) {
            this.openid = openid;
            return this;
        }

        public Builder nike(String nike) {
            this.nike = nike;
            return this;
        }

        public Builder sex(Integer sex) {
            this.sex = sex;
            return this;
        }

        public Builder provice(String provice) {
            this.provice = provice;
            return this;
        }

        public Builder city(String city) {
            this.city = city;
            return this;
        }

        public Builder country(String country) {
            this.country = country;
            return this;
        }

        public Builder headimageurl(String headimageurl) {
            this.headimageurl = headimageurl;
            return this;
        }

        public Builder unionid(String unionid) {
            this.unionid = unionid;
            return this;
        }

        public Builder numscard1(Integer numscard1) {
            this.numscard1 = numscard1;
            return this;
        }

        public Builder numscard2(Integer numscard2) {
            this.numscard2 = numscard2;
            return this;
        }

        public Builder numscard3(Integer numscard3) {
            this.numscard3 = numscard3;
            return this;
        }

        public Builder lastlogintime(Integer lastlogintime) {
            this.lastlogintime = lastlogintime;
            return this;
        }

        public Builder regtime(Integer regtime) {
            this.regtime = regtime;
            return this;
        }

        public Builder gm(Integer gm) {
            this.gm = gm;
            return this;
        }

        public Builder totalcardnum(Integer totalcardnum) {
            this.totalcardnum = totalcardnum;
            return this;
        }

        public Builder totalplaynum(Integer totalplaynum) {
            this.totalplaynum = totalplaynum;
            return this;
        }

        public Builder coins(Integer coins) {
            this.coins = coins;
            return this;
        }

        public Builder credits(Integer credits) {
            this.credits = credits;
            return this;
        }

        public Builder diamond(Integer diamond) {
            this.diamond = diamond;
            return this;
        }

        public Builder registerIp(String registerIp) {
            this.registerIp = registerIp;
            return this;
        }

        public Builder regMac(String regMac) {
            this.regMac = regMac;
            return this;
        }

        public Builder spreadId(Integer spreadId) {
            this.spreadId = spreadId;
            return this;
        }

        public Builder regChannel(String regChannel) {
            this.regChannel = regChannel;
            return this;
        }

        public Builder inviterId(Integer inviterId) {
            this.inviterId = inviterId;
            return this;
        }

        public Builder generalId(Long generalId) {
            this.generalId = generalId;
            return this;
        }

        public Builder periodEmailFlag(String periodEmailFlag) {
            this.periodEmailFlag = periodEmailFlag;
            return this;
        }

        public Builder phoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        public User build() {
            return new User(this);
        }
    }
}