package com.gojava.db.model;

import java.io.Serializable;

public class VipMoney implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_money.id
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_money.level
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_money.money
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_money.day
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_money
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_money.id
     *
     * @return the value of vip_money.id
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_money.id
     *
     * @param id the value for vip_money.id
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_money.level
     *
     * @return the value of vip_money.level
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_money.level
     *
     * @param level the value for vip_money.level
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_money.money
     *
     * @return the value of vip_money.money
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_money.money
     *
     * @param money the value for vip_money.money
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_money.day
     *
     * @return the value of vip_money.day
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_money.day
     *
     * @param day the value for vip_money.day
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setDay(Integer day) {
        this.day = day;
    }
}