package com.gojava.db.model;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.title
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.url
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Date startDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Date endDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.sort
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.state
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.code
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.title
     *
     * @return the value of activity.title
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.title
     *
     * @param title the value for activity.title
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.url
     *
     * @return the value of activity.url
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.url
     *
     * @param url the value for activity.url
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_datetime
     *
     * @return the value of activity.start_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Date getStartDatetime() {
        return startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_datetime
     *
     * @param startDatetime the value for activity.start_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_datetime
     *
     * @return the value of activity.end_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Date getEndDatetime() {
        return endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_datetime
     *
     * @param endDatetime the value for activity.end_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_datetime
     *
     * @return the value of activity.create_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_datetime
     *
     * @param createDatetime the value for activity.create_datetime
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.sort
     *
     * @return the value of activity.sort
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.sort
     *
     * @param sort the value for activity.sort
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.state
     *
     * @return the value of activity.state
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.state
     *
     * @param state the value for activity.state
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.code
     *
     * @return the value of activity.code
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.code
     *
     * @param code the value for activity.code
     *
     * @mbggenerated Fri Dec 29 11:57:31 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }
}